"""add storage object metadata

Revision ID: 715f5f1309e4
Revises: b81f5a203f27
Create Date: 2026-08-20 17:27:00.234672
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '715f5f1309e4'
down_revision: Union[str, Sequence[str], None] = 'b81f5a203f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('storage_objects',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('bucket', sa.String(length=255), nullable=False),
    sa.Column('object_key', sa.Text(), nullable=False),
    sa.Column('namespace', sa.Enum('legal_corpus', 'police_case', 'advocate_case', 'generated_document', name='storage_namespace'), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=True),
    sa.Column('case_id', sa.UUID(), nullable=True),
    sa.Column('original_filename', sa.String(length=500), nullable=False),
    sa.Column('content_type', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_storage_objects_case_id_cases'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_storage_objects_owner_id_users'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_storage_objects')),
    sa.UniqueConstraint('bucket', 'object_key', name='uq_storage_bucket_object_key')
    )
    op.create_index(op.f('ix_storage_objects_case_id'), 'storage_objects', ['case_id'], unique=False)
    op.create_index(op.f('ix_storage_objects_namespace'), 'storage_objects', ['namespace'], unique=False)
    op.create_index(op.f('ix_storage_objects_owner_id'), 'storage_objects', ['owner_id'], unique=False)
    op.create_index(op.f('ix_storage_objects_sha256'), 'storage_objects', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_storage_objects_sha256'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_owner_id'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_namespace'), table_name='storage_objects')
    op.drop_index(op.f('ix_storage_objects_case_id'), table_name='storage_objects')
    op.drop_table('storage_objects')
    sa.Enum(name='storage_namespace').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
